### ISSUE TITLE
um, what is difference between nix-env and nix configuration file

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#357]

**Comment by Gerschtli** [comment]
With nix-env you can imperatively install packages (comparable with how package manager like apt, yum, etc. are used). With the nix-on-droid.nix config file, you can declaratively install packages and configure your installation.

In the nix world, we prefer declarative over imperative because it enables easier reproducibility of your system and one single place where your installed packages are maintained.

The nix-on-droid.nix config file behaves similar to the configuration.nix file for NixOS.

More resources regarding that topic can be found at nixos.org and nix.dev.
